import LocalizedStrings from 'react-localization';

export  let strings = new LocalizedStrings({
	fin:{
		login: "Kirjaudu sisään",
		register: "Rekisteröidy",
		firstname: "Etunimi",
		surname: "Sukunimi",
		email: "Sähköposti",
		telnum: "Puhelinnumero",
		password: "Salasana",
		submit: "Vahvista",
		close: "Sulje",
		confirm: "Vahvista salasana",
		login: "Kirjaudu sisään",
		errdialpasswdmatch: "Salasana ja salasanan vahvistus täytyy olla sama",
		errdialfillall: "Täytä kaikki kentät ja yritä uudelleen",
		errdialcheckemail: "Tarkasta sähköposti",
		errdialcheckphone: "Virheellinen puhelin numero",
		nomatch: "Osoiteelle ei löytynyt sivua.",
		book: "Varaa!",
		loginstatus: "Käyttäjää ei löytynyt!",
		serveiceproviders: "Palveluntarjoajat",
		spname: "Toiminimi",
		tologin: "Kirjautumiseen",
		regsuccess: "Tilinne on luotu ",
		regfail:"Sähköposti tai puhelinnumero on jo käytössä",
		forgotpassword:"Unohditko salasanan?",
		logout:"Kirjaudu ulos",
		tooshort: "Salasana liian lyhyt",
		passwordlenght: "Salana vähintään 6 merkkiä",
		profile: "Profiili",
		profile: "Profiili",
		activityname: "Aktiviteetin nimi",
		description: "Kuvaus",
		addactivity: "Lisää aktiviteetti",
		location:"Osoite",
		shifttime: "Aika",
 		shiftdate: "Päivä",
 		price: "Hinta",
 		sport:"Laji",
	},
	en: {
		register: "Register",
		firstname: "Firstname",
		surname: "Surname",
		email: "Email",
		telnum: "Phone number",
		password: "Password",
		submit: "Submit",
		close: "Close",
		confirm: "Confirm Password",
		login: "Login",
		errdialpasswdmatch: "Passwords are not matching",
		errdialfillall: "Fill in all the fields and try again",
		errdialcheckemail: "Check email",
		errdialcheckphone: "Phone number is incorrect",
		nomatch: "404 page was not found.",
		book: "book now!",
		loginstatus: "User was not found!",
		serveiceproviders: "Serviceproviders",
		spname:"Commercial name",
		tologin:"To Login",
		regsuccess:"You have an account now. Congratulations ",
		regfail:"email or phone is already in use",
		forgotpassword:"Forgot password?",
		logout:"Logout",
		tooshort:"Password too short",
		passwordlenght: "Password must be atleast 6 characters",
		profile:"Profile",
		profile:"Profile",
		activityname: "Activity Name",
		description: "Description",
		addactivity: "Add activity",
		location:"Location",
		shifttime: "Time",
 		shiftdate: "Date",
 		price: "Price",
 		sport:"Sport",
 			
	}
});
